# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Main_GUI.ui'
##
## Created by: Qt User Interface Compiler version 6.5.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QGroupBox, QHeaderView, QLabel, QMainWindow,
    QPushButton, QSizePolicy, QTabWidget, QTableView,
    QTextEdit, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1118, 888)
        font = QFont()
        font.setPointSize(10)
        font.setBold(True)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet(u"color:black;")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.titleFrame = QFrame(self.centralwidget)
        self.titleFrame.setObjectName(u"titleFrame")
        self.titleFrame.setGeometry(QRect(10, 10, 821, 100))
        self.titleFrame.setFrameShape(QFrame.WinPanel)
        self.titleFrame.setFrameShadow(QFrame.Sunken)
        self.titleLabel = QLabel(self.titleFrame)
        self.titleLabel.setObjectName(u"titleLabel")
        self.titleLabel.setGeometry(QRect(10, 10, 801, 80))
        font1 = QFont()
        font1.setFamilies([u"Monotype Corsiva"])
        font1.setPointSize(28)
        font1.setBold(False)
        font1.setItalic(True)
        self.titleLabel.setFont(font1)
        self.titleLabel.setLayoutDirection(Qt.LeftToRight)
        self.titleLabel.setStyleSheet(u"color: rgb(0, 0, 255);")
        self.titleLabel.setAlignment(Qt.AlignCenter)
        self.logoFrame = QFrame(self.centralwidget)
        self.logoFrame.setObjectName(u"logoFrame")
        self.logoFrame.setGeometry(QRect(840, 10, 261, 100))
        self.logoFrame.setFrameShape(QFrame.WinPanel)
        self.logoFrame.setFrameShadow(QFrame.Sunken)
        self.logoLabel = QLabel(self.logoFrame)
        self.logoLabel.setObjectName(u"logoLabel")
        self.logoLabel.setGeometry(QRect(10, 20, 240, 65))
        self.logoLabel.setFont(font)
        self.logoLabel.setStyleSheet(u"color: rgb(0, 0, 255);")
        self.logoLabel.setFrameShape(QFrame.StyledPanel)
        self.logoLabel.setFrameShadow(QFrame.Plain)
        self.logoLabel.setMidLineWidth(3)
        self.logoLabel.setTextFormat(Qt.AutoText)
        self.logoLabel.setAlignment(Qt.AlignCenter)
        self.mainTabWidget = QTabWidget(self.centralwidget)
        self.mainTabWidget.setObjectName(u"mainTabWidget")
        self.mainTabWidget.setGeometry(QRect(10, 120, 1101, 761))
        self.mainTabWidget.setStyleSheet(u"background-color: rgb(240, 240, 240);")
        self.testTab = QWidget()
        self.testTab.setObjectName(u"testTab")
        self.messageGroupBox2 = QGroupBox(self.testTab)
        self.messageGroupBox2.setObjectName(u"messageGroupBox2")
        self.messageGroupBox2.setGeometry(QRect(550, 540, 531, 181))
        self.messageGroupBox2.setFont(font)
        self.messageGroupBox2.setStyleSheet(u"color:red;")
        self.messageTextEdit2 = QTextEdit(self.messageGroupBox2)
        self.messageTextEdit2.setObjectName(u"messageTextEdit2")
        self.messageTextEdit2.setGeometry(QRect(10, 20, 511, 151))
        font2 = QFont()
        font2.setPointSize(10)
        font2.setBold(True)
        font2.setItalic(False)
        self.messageTextEdit2.setFont(font2)
        self.messageTextEdit2.setStyleSheet(u"color:black;background-color:white;")
        self.sensorGroupBox = QGroupBox(self.testTab)
        self.sensorGroupBox.setObjectName(u"sensorGroupBox")
        self.sensorGroupBox.setGeometry(QRect(10, 440, 531, 91))
        self.sensorGroupBox.setFont(font)
        self.sensorGroupBox.setStyleSheet(u"color:red;")
        self.sensorLabel1 = QLabel(self.sensorGroupBox)
        self.sensorLabel1.setObjectName(u"sensorLabel1")
        self.sensorLabel1.setGeometry(QRect(10, 25, 61, 16))
        self.sensorLabel1.setFont(font)
        self.sensorLabel1.setStyleSheet(u"color:blue;")
        self.sensorComboBox1 = QComboBox(self.sensorGroupBox)
        self.sensorComboBox1.setObjectName(u"sensorComboBox1")
        self.sensorComboBox1.setGeometry(QRect(100, 20, 81, 25))
        self.sensorComboBox1.setFont(font)
        self.sensorComboBox1.setStyleSheet(u"color:black;background-color:white;")
        self.sensorButton = QPushButton(self.sensorGroupBox)
        self.sensorButton.setObjectName(u"sensorButton")
        self.sensorButton.setGeometry(QRect(200, 20, 75, 25))
        self.sensorButton.setFont(font2)
        self.sensorButton.setStyleSheet(u"color:black;")
        self.sensorLabel2 = QLabel(self.sensorGroupBox)
        self.sensorLabel2.setObjectName(u"sensorLabel2")
        self.sensorLabel2.setGeometry(QRect(10, 55, 81, 16))
        self.sensorLabel2.setFont(font)
        self.sensorLabel2.setStyleSheet(u"color:blue;")
        self.sensorComboBox2 = QComboBox(self.sensorGroupBox)
        self.sensorComboBox2.setObjectName(u"sensorComboBox2")
        self.sensorComboBox2.setGeometry(QRect(100, 50, 81, 25))
        self.sensorComboBox2.setFont(font)
        self.sensorComboBox2.setStyleSheet(u"color:black;background-color:white;")
        self.sensorLabel3 = QLabel(self.sensorGroupBox)
        self.sensorLabel3.setObjectName(u"sensorLabel3")
        self.sensorLabel3.setGeometry(QRect(200, 55, 91, 16))
        self.sensorLabel3.setFont(font)
        self.sensorLabel3.setStyleSheet(u"color:blue;")
        self.sensorComboBox3 = QComboBox(self.sensorGroupBox)
        self.sensorComboBox3.setObjectName(u"sensorComboBox3")
        self.sensorComboBox3.setGeometry(QRect(300, 50, 51, 25))
        self.sensorComboBox3.setFont(font)
        self.sensorComboBox3.setStyleSheet(u"color:black;background-color:white;")
        self.messageGroupBox1 = QGroupBox(self.testTab)
        self.messageGroupBox1.setObjectName(u"messageGroupBox1")
        self.messageGroupBox1.setGeometry(QRect(10, 540, 531, 181))
        self.messageGroupBox1.setFont(font)
        self.messageGroupBox1.setStyleSheet(u"color:red;")
        self.messageTextEdit1 = QTextEdit(self.messageGroupBox1)
        self.messageTextEdit1.setObjectName(u"messageTextEdit1")
        self.messageTextEdit1.setGeometry(QRect(10, 20, 511, 151))
        self.messageTextEdit1.setFont(font2)
        self.messageTextEdit1.setStyleSheet(u"color:black;background-color:white;")
        self.controlGroupBox = QGroupBox(self.testTab)
        self.controlGroupBox.setObjectName(u"controlGroupBox")
        self.controlGroupBox.setGeometry(QRect(560, 440, 521, 91))
        self.controlGroupBox.setFont(font)
        self.controlGroupBox.setStyleSheet(u"color:red;")
        self.readRGBButton = QPushButton(self.controlGroupBox)
        self.readRGBButton.setObjectName(u"readRGBButton")
        self.readRGBButton.setGeometry(QRect(170, 20, 81, 25))
        self.readRGBButton.setFont(font2)
        self.readRGBButton.setStyleSheet(u"color:black;")
        self.controlLabel1 = QLabel(self.controlGroupBox)
        self.controlLabel1.setObjectName(u"controlLabel1")
        self.controlLabel1.setGeometry(QRect(10, 25, 71, 16))
        self.controlLabel1.setFont(font)
        self.controlLabel1.setStyleSheet(u"color:blue;")
        self.controlComboBox1 = QComboBox(self.controlGroupBox)
        self.controlComboBox1.setObjectName(u"controlComboBox1")
        self.controlComboBox1.setGeometry(QRect(90, 20, 61, 25))
        self.controlComboBox1.setFont(font)
        self.controlComboBox1.setStyleSheet(u"color:black;background-color:white;")
        self.continuousCheckBox = QCheckBox(self.controlGroupBox)
        self.continuousCheckBox.setObjectName(u"continuousCheckBox")
        self.continuousCheckBox.setGeometry(QRect(260, 25, 131, 20))
        self.continuousCheckBox.setFont(font)
        self.continuousCheckBox.setStyleSheet(u"color:blue;")
        self.controlLabel2 = QLabel(self.controlGroupBox)
        self.controlLabel2.setObjectName(u"controlLabel2")
        self.controlLabel2.setGeometry(QRect(10, 55, 81, 16))
        self.controlLabel2.setFont(font)
        self.controlLabel2.setStyleSheet(u"color:blue;")
        self.controlComboBox2 = QComboBox(self.controlGroupBox)
        self.controlComboBox2.setObjectName(u"controlComboBox2")
        self.controlComboBox2.setGeometry(QRect(90, 50, 61, 25))
        self.controlComboBox2.setFont(font)
        self.controlComboBox2.setStyleSheet(u"color:black;background-color:white;")
        self.controlLabel3 = QLabel(self.controlGroupBox)
        self.controlLabel3.setObjectName(u"controlLabel3")
        self.controlLabel3.setGeometry(QRect(170, 55, 51, 16))
        self.controlLabel3.setFont(font)
        self.controlLabel3.setStyleSheet(u"color:blue;")
        self.controlComboBox3 = QComboBox(self.controlGroupBox)
        self.controlComboBox3.setObjectName(u"controlComboBox3")
        self.controlComboBox3.setGeometry(QRect(250, 50, 61, 25))
        self.controlComboBox3.setFont(font)
        self.controlComboBox3.setStyleSheet(u"color:black;background-color:white;")
        self.messageGroupBox3 = QGroupBox(self.testTab)
        self.messageGroupBox3.setObjectName(u"messageGroupBox3")
        self.messageGroupBox3.setGeometry(QRect(10, 10, 1071, 421))
        self.messageGroupBox3.setFont(font)
        self.messageGroupBox3.setStyleSheet(u"color:red;")
        self.sensorTableView = QTableView(self.messageGroupBox3)
        self.sensorTableView.setObjectName(u"sensorTableView")
        self.sensorTableView.setGeometry(QRect(10, 20, 1051, 391))
        self.sensorTableView.setStyleSheet(u"color:black;background-color:white;")
        self.mainTabWidget.addTab(self.testTab, "")
        self.aboutTab = QWidget()
        self.aboutTab.setObjectName(u"aboutTab")
        self.testarchPanel = QTextEdit(self.aboutTab)
        self.testarchPanel.setObjectName(u"testarchPanel")
        self.testarchPanel.setEnabled(False)
        self.testarchPanel.setGeometry(QRect(20, 10, 641, 711))
        self.releasenoteTextEdit = QTextEdit(self.aboutTab)
        self.releasenoteTextEdit.setObjectName(u"releasenoteTextEdit")
        self.releasenoteTextEdit.setGeometry(QRect(30, 20, 621, 691))
        self.releasenoteTextEdit.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.aboutGroupBox = QGroupBox(self.aboutTab)
        self.aboutGroupBox.setObjectName(u"aboutGroupBox")
        self.aboutGroupBox.setGeometry(QRect(670, 10, 411, 711))
        font3 = QFont()
        font3.setPointSize(10)
        self.aboutGroupBox.setFont(font3)
        self.aboutGroupBox.setStyleSheet(u"color: rgb(255, 0,0);")
        self.aboutLabel1 = QLabel(self.aboutGroupBox)
        self.aboutLabel1.setObjectName(u"aboutLabel1")
        self.aboutLabel1.setGeometry(QRect(20, 30, 381, 20))
        font4 = QFont()
        font4.setPointSize(10)
        font4.setBold(False)
        self.aboutLabel1.setFont(font4)
        self.aboutLabel1.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.aboutLabel1.setTextFormat(Qt.AutoText)
        self.aboutLabel2 = QLabel(self.aboutGroupBox)
        self.aboutLabel2.setObjectName(u"aboutLabel2")
        self.aboutLabel2.setGeometry(QRect(20, 55, 201, 16))
        self.aboutLabel2.setFont(font4)
        self.aboutLabel2.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.aboutLabel2.setTextFormat(Qt.AutoText)
        self.aboutLabel3 = QLabel(self.aboutGroupBox)
        self.aboutLabel3.setObjectName(u"aboutLabel3")
        self.aboutLabel3.setGeometry(QRect(20, 80, 131, 16))
        self.aboutLabel3.setFont(font4)
        self.aboutLabel3.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.aboutLabel3.setTextFormat(Qt.AutoText)
        self.authorLabel1 = QLabel(self.aboutGroupBox)
        self.authorLabel1.setObjectName(u"authorLabel1")
        self.authorLabel1.setGeometry(QRect(20, 620, 191, 20))
        self.authorLabel1.setFont(font4)
        self.authorLabel1.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.authorLabel1.setTextFormat(Qt.AutoText)
        self.authorLabel2 = QLabel(self.aboutGroupBox)
        self.authorLabel2.setObjectName(u"authorLabel2")
        self.authorLabel2.setGeometry(QRect(20, 650, 191, 20))
        self.authorLabel2.setFont(font4)
        self.authorLabel2.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.authorLabel2.setTextFormat(Qt.AutoText)
        self.authorLabel3 = QLabel(self.aboutGroupBox)
        self.authorLabel3.setObjectName(u"authorLabel3")
        self.authorLabel3.setGeometry(QRect(20, 680, 191, 20))
        self.authorLabel3.setFont(font4)
        self.authorLabel3.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.authorLabel3.setTextFormat(Qt.AutoText)
        self.mainTabWidget.addTab(self.aboutTab, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.mainTabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.titleLabel.setText(QCoreApplication.translate("MainWindow", u"LED Sensor Utility (ASC)", None))
        self.logoLabel.setText(QCoreApplication.translate("MainWindow", u"Logo", None))
        self.messageGroupBox2.setTitle(QCoreApplication.translate("MainWindow", u" Sensor Message ", None))
        self.sensorGroupBox.setTitle(QCoreApplication.translate("MainWindow", u" Sensor  ", None))
        self.sensorLabel1.setText(QCoreApplication.translate("MainWindow", u"COM Port", None))
        self.sensorButton.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.sensorLabel2.setText(QCoreApplication.translate("MainWindow", u"Sensor Type", None))
        self.sensorLabel3.setText(QCoreApplication.translate("MainWindow", u"Slave Address", None))
        self.messageGroupBox1.setTitle(QCoreApplication.translate("MainWindow", u" Message ", None))
        self.controlGroupBox.setTitle(QCoreApplication.translate("MainWindow", u" Control ", None))
        self.readRGBButton.setText(QCoreApplication.translate("MainWindow", u"Read Once", None))
        self.controlLabel1.setText(QCoreApplication.translate("MainWindow", u"Sensor No", None))
        self.continuousCheckBox.setText(QCoreApplication.translate("MainWindow", u"Continuous Read", None))
        self.controlLabel2.setText(QCoreApplication.translate("MainWindow", u"Board Delay", None))
        self.controlLabel3.setText(QCoreApplication.translate("MainWindow", u"Interval", None))
        self.messageGroupBox3.setTitle(QCoreApplication.translate("MainWindow", u" Sensor Information ", None))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.testTab), QCoreApplication.translate("MainWindow", u"Test", None))
        self.aboutGroupBox.setTitle(QCoreApplication.translate("MainWindow", u" About ", None))
        self.aboutLabel1.setText(QCoreApplication.translate("MainWindow", u"LED Sensor Utility (ASC)  Version 1.0.0.0", None))
        self.aboutLabel2.setText(QCoreApplication.translate("MainWindow", u"Accton Technology Corporation.", None))
        self.aboutLabel3.setText(QCoreApplication.translate("MainWindow", u"All Rights Reserved.", None))
        self.authorLabel1.setText(QCoreApplication.translate("MainWindow", u"Author: \u6731\u5efa\u676d(Max Chu)", None))
        self.authorLabel2.setText(QCoreApplication.translate("MainWindow", u"TEL: +886-3-5770270#2422", None))
        self.authorLabel3.setText(QCoreApplication.translate("MainWindow", u"E-Mail: max_chu@accton.com", None))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.aboutTab), QCoreApplication.translate("MainWindow", u"About", None))
    # retranslateUi

